---
env:
  browser: true
  es2021: true
  jest: true
extends:
  - eslint:recommended
  - airbnb-base
  - prettier
  - plugin:jest/recommended
  - plugin:jest/style
plugins:
  - jest
parser: "@babel/eslint-parser"
parserOptions:
  ecmaVersion: 12
  sourceType: module
globals:
  d3: true
  dagre: true
rules:
  no-plusplus: "off"
  import/extensions: "off"
  no-param-reassign: "off"
  no-restricted-syntax: "off"
  no-underscore-dangle: "off"
  guard-for-in: "off"
  no-use-before-define: "off"
