---
env:
  browser: true
  es2021: true
  mocha: true
extends:
  - eslint:recommended
  - airbnb-base
  - prettier
parser: '@babel/eslint-parser'
parserOptions:
  ecmaVersion: 12
  sourceType: module
globals:
  d3: true
rules:
  no-plusplus: 'off'
  import/extensions: 'off'
  no-param-reassign: 'off'
  no-restricted-syntax: 'off'
  no-underscore-dangle: 'off'
  guard-for-in: 'off'
